In [21]:
import pandas as pd
import numpy as np
import plotly.plotly as py
import cufflinks as cf 
import matplotlib.pyplot as plt
from pivottablejs import pivot_ui

class Index() :
    ALGORITHME = 0
    LANGUAGE = 1
    COMPILEFLAG = 2
    PARAM = 3
    INNERLOOP = 4 
#df = pd.DataFrame()
columns=['language','compilflag','param','innerloop','value']

l= []
files= !(ls *power) # file format : 'algo>.<language>.<compilflag>.<param>.<innerloop>.power
i = 0 
for file in files : 
    f=!(cat $file)
    infos = file.split('.')

    infos[Index.INNERLOOP] = int(infos[Index.INNERLOOP])
    for line in f :
        row = infos[1:-1]
        
          
        row.append(float(line))
        l.append(tuple(row))
    
df = pd.DataFrame(l,columns=columns)

In [20]:
x=df[df.language == 'c']
x.groupby(['innerloop']).mean()
py.iplot([{  'x': [i for i in range(10) ],
    'name':item,
    'y':x[x.innerloop==item].value
    } for item in x.innerloop.drop_duplicates()],filename='simple-test')

In [31]:
x= df.groupby(['language','compilflag','innerloop']).mean()
x=x.drop(['java'])
data=x.unstack(level=[0,1])
data=data.value
data
data['c']['o1']
py.iplot([{
    'x':data.index,
    'y':data[col],
    'name':col[0]+':'+col[1]
    }  for col in data.columns  ],filename='simple-test')

In [27]:
x=df
x= x.groupby(['language','compilflag','innerloop']).mean()
x=x.drop(['java'])
x

                                     value
language compilflag innerloop
c        latest     1               0.0000
                    2            1458.1619
                    4            5693.6500
                    8           14299.2200
                    16          31424.8600
                    32          66001.7800
         o1         1               0.0000
                    2            1290.7174
                    4            5803.0290
                    8           14415.8400
                    16          31466.5200
                    32          65911.3200
         o2         1               0.0000
                    2            1109.4786
                    4            5485.3890
                    8           14398.3600
                    16          31930.0400
                    32          66945.3500
         o3         1               0.0000
                    2            1457.6242
                    4            5650.0460
                    8           14656.9700
                    16          31706.8100
                    32          66528.9100
cpp      latest     1               0.0000
                    2            1751.8440
                    4            6464.8530
                    8           15128.4500
                    16          32666.2700
                    32          68713.8200
...                                    ...
python   latest     1             881.3974
                    2            4817.9850
                    4           12767.6800
                    8           28230.2000
                    16          59289.4100
                    32         121219.6000
rust     latest     1               0.0000
                    2            1473.5150
                    4            5831.3930
                    8           14415.0700
                    16          32189.5200
                    32          67141.4300
         o1         1               0.0000
                    2            1260.8834
                    4            5662.9680
                    8           14038.0600
                    16          31454.6900
                    32          65659.2200
         o2         1               0.0000
                    2            1482.4377
                    4            5897.5570
                    8           14484.6800
                    16          31923.5700
                    32          66075.8400
         o3         1               0.0000
                    2            1460.3081
                    4            5748.0400
                    8           14227.4300
                    16          31875.1300
                    32          66377.6100

[84 rows x 1 columns]